### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by MilesBHuff** [ByteZ1337/ParticleLib#17]
After updating to v1.6.4, I started getting this error on startup:
```
[22:00:38] [Server thread/ERROR]: Could not load 'plugins/ParticleLib.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[patched_1.16.5.jar:git-Paper-783]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.16.5.jar:git-Paper-783]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-783]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 7 more
```
The above error occurs every time I start up the server.
I am running Paper 1.16.5.

**Comment by MilesBHuff** [comment]
Rolled back, and found that the error is also happening with v1.6.3.  Could it be related to recent changes in Paper?
EDIT:  Also failing for 1.5.1, weirdly.
I know 1.5.1 and 1.6.3 were working on my server in the past.

**Comment by ByteZ1337** [comment]
As the error states: ``Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml``. 
New ParticleLib versions no longer contain a plugin version, since spigot added a [Library Loader](https://www.spigotmc.org/threads/spigot-bungeecord-1-17-1-17-1.510208/#post-4184317).

**Comment by MilesBHuff** [comment]
Any idea why this issue would only be cropping up now?  And how to fix?

**Comment by ByteZ1337** [comment]
Include ParticleLib in your plugin.

**Comment by MilesBHuff** [comment]
I'm just a server owner -- I've always had to use the headless version of ParticleLib.  Should I no longer be doing that?

**Comment by ByteZ1337** [comment]
Contact the plugin developer and tell them to shade ParticleLib into their plugin or download an [outdated plugin version](https://github.com/ByteZ1337/ParticleLib/releases/download/1.5.1/ParticleLib-Plugin.jar) of ParticleLib.
