### ISSUE TITLE
Problem with ParticleMappings class

### ISSUE THREAD

**Issue by Gennario** [ByteZ1337/ParticleLib#27]
Hello. I have the code from particle library in my code, but since the last update it stopped working and doesn't cooperate at all, please help.

error:
```
19:45:41[WARN] [RotatingHeadsPRO] Plugin RotatingHeadsPRO v1.0.1 generated an exception while executing task 1762
java.lang.ExceptionInInitializerError: null
at xyz.xenondevs.particle.ParticleConstants.<clinit>(ParticleConstants.java:246) ~[RotatingHeadsPRO.jar:?]
at xyz.xenondevs.particle.ParticleEffect.getNMSObject(ParticleEffect.java:1328) ~[RotatingHeadsPRO.jar:?]
at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Unknown Source) ~[?:?]
at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source) ~[?:?]
at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
at xyz.xenondevs.particle.ParticleEffect.<clinit>(ParticleEffect.java:1235) ~[RotatingHeadsPRO.jar:?]
at cz.gennario.rotatingheads.particles.ParticleLoader.loadFromString(ParticleLoader.java:22) ~[RotatingHeadsPRO.jar:?]
at cz.gennario.rotatingheads.system.Head.loadParticles(Head.java:194) ~[RotatingHeadsPRO.jar:?]
at cz.gennario.rotatingheads.system.Head.<init>(Head.java:130) ~[RotatingHeadsPRO.jar:?]
at cz.gennario.rotatingheads.Main.loadHeads(Main.java:165) ~[RotatingHeadsPRO.jar:?]
at cz.gennario.rotatingheads.Main$1.run(Main.java:118) ~[RotatingHeadsPRO.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[server.jar:git-Purpur-1428]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[server.jar:git-Purpur-1428]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Purpur-1428]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load mappings
at xyz.xenondevs.particle.ParticleMappings.<clinit>(ParticleMappings.java:62) ~[RotatingHeadsPRO.jar:?]
... 23 more
Caused by: java.lang.NullPointerException
at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
at xyz.xenondevs.particle.ParticleMappings.<clinit>(ParticleMappings.java:53) ~[RotatingHeadsPRO.jar:?]
... 23 more
```

**Comment by ByteZ1337** [comment]
Include the mappings.json in your resources
